[package]
name = "maolan-widgets"
version = "0.0.35"
edition = "2024"
description = "Widgets used for Maolan DAW"
license = "BSD-2-Clause"
readme = "README.md"
repository = "https://github.com/maolan/widgets"
homepage = "https://maolan.github.io"
documentation = "https://docs.rs/maolan-widgets"
keywords = ["audio", "midi", "daw", "widgets"]
categories = ["multimedia::audio"]

[dependencies]
iced = { version = "0.14.0", features = ["advanced", "canvas", "image", "lazy", "tokio"] }
iced_aw = "0.14.1"
iced_drop = { version = "0.2.16", features = ["helpers"] }
iced_fonts = { version = "0.3.0", features = ["lucide"] }
serde = { version = "1.0.229", features = ["derive"] }
symphonia = { version = "0.5.4", features = ["wav"] }
